version: '3'

services:
  my5gcore-ue:
    container_name: non3gpp2
    build:
      context: ../containers/nf_ue
      args:
        DEBUG_TOOLS: "true"
    volumes:
      - ../samples/iotsgdw/config:/my5gcore/config
      - ../bin/configs.sh:/my5gcore/init.sh
    environment:
      GIN_MODE: release
    extra_hosts:
      - "non3gpp2:192.168.127.3"
      - "n3iwf:192.168.127.1"
    networks:
     5gcorenetwork:
       aliases:
         - non3gpp2.my5Gcore.org
    cap_add:
      - ALL
    command: sh -c "./init.sh StartupUe 10.100.130.10"

networks:
  5gcorenetwork:
     external: true
