---
- name: Get IOSDGW-Orquestrator Code 
  git:
    repo: "{{ iotsdgw_rep }}" 
    dest: "{{ iotsdgw_dir }}"
    update: yes
    force: yes

- name: Clear All Docker Env
  ansible.builtin.shell: docker system prune --force --all
  args:
    executable: /bin/bash
  become: yes

- name: Make my5gore base core container
  make:
     chdir: "{{ iotsdgw_dir }}"
     target: base_my5gcore
  become: yes

- name: Make my5gore base ue  container
  make:
     chdir: "{{ iotsdgw_dir }}"
     target: base_ue
  become: yes
