---
- name: Get IOSDGW-Orquestrator Code 
  git:
    repo: "{{ iotsdgw_rep }}" 
    dest: "{{ iotsdgw_dir }}"

- name: Make my5gore base core container
  make:
     chdir: "{{ iotsdgw_dir }}"
     target: base_my5gcore
  become: yes


- name: Make my5gore base ue  container
  make:
     chdir: "{{ iotsdgw_dir }}"
     target: base_ue
  become: yes    


- name: Copy volumes config to scenaryOne 
  ansible.builtin.copy:
    src:       
 
     
