---
- hosts: all
  become: true
  vars:
    dir_metrics: /home/teste/temp/iotsdgw/orquestrators/scenary1/volumes/metrics
    dir_dst: cenario1
    number_of_nodes: "e{{ devs }}"
  roles:
    - collect