---
- hosts: all    
  become: true
  vars:
    dir_metrics: /home/teste/temp/iotsdgw/orquestrators/scenary2/volumes/metrics
    dir_dst: cenario2
    number_of_nodes: "e{{ devs }}"
  roles:
    - collect